/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mocks from "./mocks";
export * as sTokenSol from "./sToken.sol";
export { LendingPool__factory } from "./LendingPool__factory";
